/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project_pembayaran_spp.application;

//import org.apache.pdfbox.pdmodel.PDDocument;
//import org.apache.pdfbox.pdmodel.PDPage;
//import org.apache.pdfbox.pdmodel.PDPageContentStream;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileOutputStream;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormatSymbols;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentListener;
import javax.swing.event.UndoableEditListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import javax.swing.text.Element;
import javax.swing.text.Position;
import javax.swing.text.Segment;
import project_pembayaran_spp.controllers.Kelas_controller;
import project_pembayaran_spp.controllers.Petugas_controller;
import project_pembayaran_spp.controllers.Siswa_controller;
import project_pembayaran_spp.controllers.Spp_controller;
import project_pembayaran_spp.controllers.pembayaran_controller;
import project_pembayaran_spp.model.Kelas_model;
import project_pembayaran_spp.services.database_process.SELECT_DATABASE;
import project_pembayaran_spp.services.kelas_service;

/**
 *
 * @author Rafli
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form DashboardSiswa
     */
    public Dashboard() {
        fillComboBoxSppPembayaran();
        fillComboBoxPetugas();
        fillComboBoxSiswa();
        fillComboBoxSpp();
        fillComboBoxKelas();
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jDatePickerUtil1 = new org.jdatepicker.util.JDatePickerUtil();
        jDatePickerUtil2 = new org.jdatepicker.util.JDatePickerUtil();
        jDatePickerUtil3 = new org.jdatepicker.util.JDatePickerUtil();
        jDatePickerUtil4 = new org.jdatepicker.util.JDatePickerUtil();
        dateComponentFormatter1 = new org.jdatepicker.impl.DateComponentFormatter();
        jDatePickerUtil5 = new org.jdatepicker.util.JDatePickerUtil();
        jDateComponentFactory1 = new org.jdatepicker.JDateComponentFactory();
        jDatePickerUtil6 = new org.jdatepicker.util.JDatePickerUtil();
        jDatePickerUtil7 = new org.jdatepicker.util.JDatePickerUtil();
        jDatePickerUtil8 = new org.jdatepicker.util.JDatePickerUtil();
        dateComponentFormatter2 = new org.jdatepicker.impl.DateComponentFormatter();
        dateComponentFormatter3 = new org.jdatepicker.impl.DateComponentFormatter();
        jDatePickerUtil9 = new org.jdatepicker.util.JDatePickerUtil();
        jDatePickerUtil10 = new org.jdatepicker.util.JDatePickerUtil();
        jPanel1 = new javax.swing.JPanel();
        DASHBOARD = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        SimpanClass = new javax.swing.JButton();
        ClassNameColumn = new javax.swing.JTextField();
        KopetensiColumn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        UpdateClass = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableClass = new javax.swing.JTable();
        ClearClass = new javax.swing.JButton();
        DeleteClass = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        SppTahunColumn = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        SppNominalColumn = new javax.swing.JTextField();
        ClearClass1 = new javax.swing.JButton();
        DeleteSpp = new javax.swing.JButton();
        UpdateSpp = new javax.swing.JButton();
        SimpanSpp = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableSpp = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        PetugasUsernameColumn = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        PetugasNameColumn = new javax.swing.JTextField();
        ClearClass2 = new javax.swing.JButton();
        DeletePetugas = new javax.swing.JButton();
        UpdatePetugas = new javax.swing.JButton();
        SimpanPetugas = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablePetugas = new javax.swing.JTable();
        PetugasLevelColumn = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        SiswaNisnColumn = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        SiswaNisColumn = new javax.swing.JTextField();
        ClearClass3 = new javax.swing.JButton();
        DeleteSiswa = new javax.swing.JButton();
        UpdateSiswa = new javax.swing.JButton();
        SimpanSiswa = new javax.swing.JButton();
        SiswaNameColumn = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        SiswaKelasColumnItem = new javax.swing.JComboBox<>();
        SiswaAlamatColumn = new javax.swing.JTextField();
        SiswaTelpColumn = new javax.swing.JTextField();
        SiswaSppColumnItem = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        TableSiswa = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        Petugas = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        ClearClass4 = new javax.swing.JButton();
        DeleteSiswa1 = new javax.swing.JButton();
        UpdateSiswa1 = new javax.swing.JButton();
        SimpanPembayaran = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        TablePembayaran = new javax.swing.JTable();
        PembayaranPetugasColumn = new javax.swing.JComboBox<>();
        PembayaranNominalColumn = new javax.swing.JTextField();
        PembayaranSiswaColumn = new javax.swing.JComboBox<>();
        PembayaranSppColumn = new javax.swing.JComboBox<>();
        jDatePembayaran = new com.toedter.calendar.JDateChooser();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 258, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(227, 227, 227));

        SimpanClass.setFont(new java.awt.Font("Snap ITC", 1, 14)); // NOI18N
        SimpanClass.setText("SIMPAN");
        SimpanClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanClassActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Snap ITC", 1, 18)); // NOI18N
        jLabel2.setText("Nama Kelas :");

        jLabel3.setFont(new java.awt.Font("Snap ITC", 1, 18)); // NOI18N
        jLabel3.setText("Kopetensi   :");

        UpdateClass.setFont(new java.awt.Font("Snap ITC", 1, 14)); // NOI18N
        UpdateClass.setText("UPDATE");
        UpdateClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateClassActionPerformed(evt);
            }
        });

        TableClass.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama Kelas", "Kompetensi Keahlian"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableClass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableClassMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableClass);

        ClearClass.setFont(new java.awt.Font("Snap ITC", 1, 14)); // NOI18N
        ClearClass.setText("CLEAR");
        ClearClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearClassActionPerformed(evt);
            }
        });

        DeleteClass.setFont(new java.awt.Font("Snap ITC", 1, 14)); // NOI18N
        DeleteClass.setText("HAPUS");
        DeleteClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteClassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap(351, Short.MAX_VALUE)
                        .addComponent(ClearClass, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DeleteClass, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(UpdateClass, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SimpanClass, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(KopetensiColumn))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(ClassNameColumn)))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClassNameColumn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KopetensiColumn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateClass, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SimpanClass, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClearClass, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteClass, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DASHBOARD.addTab("KELAS", jPanel5);

        jLabel4.setFont(new java.awt.Font("Snap ITC", 1, 18)); // NOI18N
        jLabel4.setText("TAHUN :");

        jLabel5.setFont(new java.awt.Font("Snap ITC", 1, 18)); // NOI18N
        jLabel5.setText("NOMINAL   :");

        ClearClass1.setFont(new java.awt.Font("Snap ITC", 1, 14)); // NOI18N
        ClearClass1.setText("CLEAR");
        ClearClass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearClass1ActionPerformed(evt);
            }
        });

        DeleteSpp.setFont(new java.awt.Font("Snap ITC", 1, 14)); // NOI18N
        DeleteSpp.setText("HAPUS");
        DeleteSpp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteSppActionPerformed(evt);
            }
        });

        UpdateSpp.setFont(new java.awt.Font("Snap ITC", 1, 14)); // NOI18N
        UpdateSpp.setText("UPDATE");
        UpdateSpp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateSppActionPerformed(evt);
            }
        });

        SimpanSpp.setFont(new java.awt.Font("Snap ITC", 1, 14)); // NOI18N
        SimpanSpp.setText("SIMPAN");
        SimpanSpp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanSppActionPerformed(evt);
            }
        });

        TableSpp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tahun", "Nominal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableSpp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableSppMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableSpp);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(351, Short.MAX_VALUE)
                        .addComponent(ClearClass1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DeleteSpp, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(UpdateSpp, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SimpanSpp, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SppTahunColumn)
                            .addComponent(SppNominalColumn))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SppTahunColumn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SppNominalColumn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateSpp, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SimpanSpp, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClearClass1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteSpp, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DASHBOARD.addTab("SPP", jPanel2);

        jLabel6.setFont(new java.awt.Font("Snap ITC", 1, 18)); // NOI18N
        jLabel6.setText("Username :");

        jLabel7.setFont(new java.awt.Font("Snap ITC", 1, 18)); // NOI18N
        jLabel7.setText("Name Petugas   :");

        ClearClass2.setFont(new java.awt.Font("Snap ITC", 1, 14)); // NOI18N
        ClearClass2.setText("CLEAR");
        ClearClass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearClass2ActionPerformed(evt);
            }
        });

        DeletePetugas.setFont(new java.awt.Font("Snap ITC", 1, 14)); // NOI18N
        DeletePetugas.setText("HAPUS");
        DeletePetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletePetugasActionPerformed(evt);
            }
        });

        UpdatePetugas.setFont(new java.awt.Font("Snap ITC", 1, 14)); // NOI18N
        UpdatePetugas.setText("UPDATE");
        UpdatePetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatePetugasActionPerformed(evt);
            }
        });

        SimpanPetugas.setFont(new java.awt.Font("Snap ITC", 1, 14)); // NOI18N
        SimpanPetugas.setText("SIMPAN");
        SimpanPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanPetugasActionPerformed(evt);
            }
        });

        TablePetugas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Username", "Nama_Petugas", "Level"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablePetugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablePetugasMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TablePetugas);

        jLabel8.setFont(new java.awt.Font("Snap ITC", 1, 18)); // NOI18N
        jLabel8.setText("Level :");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(0, 306, Short.MAX_VALUE)
                                .addComponent(ClearClass2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DeletePetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(UpdatePetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SimpanPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PetugasNameColumn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                            .addComponent(PetugasUsernameColumn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PetugasLevelColumn, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PetugasUsernameColumn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PetugasNameColumn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PetugasLevelColumn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdatePetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SimpanPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClearClass2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeletePetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 965, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        DASHBOARD.addTab("PETUGAS", jPanel4);

        jLabel9.setFont(new java.awt.Font("Snap ITC", 1, 18)); // NOI18N
        jLabel9.setText("Nisn :");

        jLabel10.setFont(new java.awt.Font("Snap ITC", 1, 18)); // NOI18N
        jLabel10.setText("Nis   :");

        ClearClass3.setFont(new java.awt.Font("Snap ITC", 1, 14)); // NOI18N
        ClearClass3.setText("CLEAR");
        ClearClass3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearClass3ActionPerformed(evt);
            }
        });

        DeleteSiswa.setFont(new java.awt.Font("Snap ITC", 1, 14)); // NOI18N
        DeleteSiswa.setText("HAPUS");
        DeleteSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteSiswaActionPerformed(evt);
            }
        });

        UpdateSiswa.setFont(new java.awt.Font("Snap ITC", 1, 14)); // NOI18N
        UpdateSiswa.setText("UPDATE");
        UpdateSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateSiswaActionPerformed(evt);
            }
        });

        SimpanSiswa.setFont(new java.awt.Font("Snap ITC", 1, 14)); // NOI18N
        SimpanSiswa.setText("SIMPAN");
        SimpanSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanSiswaActionPerformed(evt);
            }
        });

        SiswaNameColumn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiswaNameColumnActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Snap ITC", 1, 18)); // NOI18N
        jLabel11.setText("Nama :");

        jLabel12.setFont(new java.awt.Font("Snap ITC", 1, 18)); // NOI18N
        jLabel12.setText("Kelas :");

        jLabel13.setFont(new java.awt.Font("Snap ITC", 1, 18)); // NOI18N
        jLabel13.setText("Alamat :");

        jLabel14.setFont(new java.awt.Font("Snap ITC", 1, 18)); // NOI18N
        jLabel14.setText("Telp :");

        jLabel15.setFont(new java.awt.Font("Snap ITC", 1, 18)); // NOI18N
        jLabel15.setText("Spp :");

        SiswaKelasColumnItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        SiswaKelasColumnItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiswaKelasColumnItemActionPerformed(evt);
            }
        });

        SiswaSppColumnItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SiswaNisColumn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                            .addComponent(SiswaNisnColumn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SiswaNameColumn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SiswaKelasColumnItem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(152, 308, Short.MAX_VALUE)
                        .addComponent(ClearClass3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DeleteSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(UpdateSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SimpanSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(107, 107, 107)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SiswaAlamatColumn)
                            .addComponent(SiswaTelpColumn)
                            .addComponent(SiswaSppColumnItem, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SiswaNisnColumn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SiswaNisColumn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SiswaNameColumn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SiswaKelasColumnItem, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addGap(7, 7, 7))
                    .addComponent(SiswaAlamatColumn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SiswaTelpColumn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SiswaSppColumnItem, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SimpanSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClearClass3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        TableSiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nisn", "Nis", "Nama", "Alamat", "No_tlp", "Spp", "Kelas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableSiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableSiswaMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(TableSiswa);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 953, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(429, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(68, Short.MAX_VALUE)))
        );

        DASHBOARD.addTab("SISWA", jPanel7);

        Petugas.setFont(new java.awt.Font("Snap ITC", 1, 18)); // NOI18N
        Petugas.setText("Petugas :");

        jLabel17.setFont(new java.awt.Font("Snap ITC", 1, 18)); // NOI18N
        jLabel17.setText("Siswa   :");

        ClearClass4.setFont(new java.awt.Font("Snap ITC", 1, 14)); // NOI18N
        ClearClass4.setText("CLEAR");
        ClearClass4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearClass4ActionPerformed(evt);
            }
        });

        DeleteSiswa1.setFont(new java.awt.Font("Snap ITC", 1, 14)); // NOI18N
        DeleteSiswa1.setText("HAPUS");
        DeleteSiswa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteSiswa1ActionPerformed(evt);
            }
        });

        UpdateSiswa1.setFont(new java.awt.Font("Snap ITC", 1, 14)); // NOI18N
        UpdateSiswa1.setText("PRINT");
        UpdateSiswa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateSiswa1ActionPerformed(evt);
            }
        });

        SimpanPembayaran.setFont(new java.awt.Font("Snap ITC", 1, 14)); // NOI18N
        SimpanPembayaran.setText("SIMPAN");
        SimpanPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanPembayaranActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Snap ITC", 1, 18)); // NOI18N
        jLabel18.setText("Tanggal :");

        jLabel21.setFont(new java.awt.Font("Snap ITC", 1, 18)); // NOI18N
        jLabel21.setText("Spp :");

        jLabel22.setFont(new java.awt.Font("Snap ITC", 1, 18)); // NOI18N
        jLabel22.setText("Nominal :");

        TablePembayaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Petugas", "Siswa", "Tanggal", "Bulan", "Tahun", "Spp", "Nominal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablePembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablePembayaranMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(TablePembayaran);

        PembayaranPetugasColumn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        PembayaranPetugasColumn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PembayaranPetugasColumnActionPerformed(evt);
            }
        });

        PembayaranSiswaColumn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        PembayaranSiswaColumn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PembayaranSiswaColumnActionPerformed(evt);
            }
        });

        PembayaranSppColumn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        PembayaranSppColumn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PembayaranSppColumnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Petugas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PembayaranPetugasColumn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PembayaranSiswaColumn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PembayaranNominalColumn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(171, 339, Short.MAX_VALUE)
                        .addComponent(ClearClass4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DeleteSiswa1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(UpdateSiswa1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SimpanPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 941, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                                .addGap(6, 259, Short.MAX_VALUE)
                                .addComponent(jDatePembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(PembayaranSppColumn, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Petugas)
                    .addComponent(PembayaranPetugasColumn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PembayaranSiswaColumn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDatePembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PembayaranSppColumn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(12, 12, 12)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PembayaranNominalColumn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateSiswa1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SimpanPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClearClass4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteSiswa1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 965, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        DASHBOARD.addTab("PEMBAYARAN", jPanel9);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DASHBOARD)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DASHBOARD)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateClassActionPerformed
        // TODO add your handling code here:
        String ClassName = ClassNameColumn.getText();
        String Kompetensi = KopetensiColumn.getText();
        int selectedRow = TableClass.getSelectedRow();
        String ID = (String) TableClass.getValueAt(selectedRow, 0);
        DefaultTableModel tableModel = (DefaultTableModel) TableClass.getModel();

        if (ClassName.isEmpty() || Kompetensi.isEmpty()) {
            JOptionPane.showConfirmDialog(null, "Error: Input cannot be empty.");
            return;
        } else {
            Kelas_controller controller = new Kelas_controller();
            controller.updateKelasAction(ClassName, Kompetensi, selectedRow, ID, tableModel);
        }
    }//GEN-LAST:event_UpdateClassActionPerformed

    private void SimpanClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanClassActionPerformed
        // TODO add your handling code here:
        String ClassName = ClassNameColumn.getText();
        String Kompetensi = KopetensiColumn.getText();
        DefaultTableModel tableModel = (DefaultTableModel) TableClass.getModel();

        if (ClassName.isEmpty() || Kompetensi.isEmpty()) {
            JOptionPane.showConfirmDialog(null, "Error: Input cannot be empty.");
            return;
        } else {
            Kelas_controller controller = new Kelas_controller();
            controller.insertKelasAction(ClassName, Kompetensi, tableModel);
        }

    }//GEN-LAST:event_SimpanClassActionPerformed

    private void TableClassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableClassMouseClicked
        Integer row = TableClass.getSelectedRow();

        if (row < 0) {
        } else {
            String ID = (String) TableClass.getValueAt(row, 0);
            SELECT_DATABASE table = new SELECT_DATABASE();
            ResultSet data = table.getOneData("Kelas", ID);

            try {
                if (data.next()) {
                    String Name = data.getString("Nama");
                    String Kompetensi = data.getString("Kompetensi");

                    System.out.println("DATA ROWS Nama: " + Name);
                    ClassNameColumn.setText(Name);
                    KopetensiColumn.setText(Kompetensi);

                } else {
                    System.out.println("Tidak ada data yang ditemukan.");
                }
            } catch (SQLException ex) {
                Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    if (data != null) {
                        data.close();
                    }
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        }

    }//GEN-LAST:event_TableClassMouseClicked

    private void ClearClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClearClassActionPerformed

    private void DeleteClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteClassActionPerformed
        // TODO add your handling code here:
        int selectedRow = TableClass.getSelectedRow();
        String ID = (String) TableClass.getValueAt(selectedRow, 0);
        DefaultTableModel tableModel = (DefaultTableModel) TableClass.getModel();

        Kelas_controller controller = new Kelas_controller();
        controller.deleteKelasAction(selectedRow, ID, tableModel);
    }//GEN-LAST:event_DeleteClassActionPerformed

    private void ClearClass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearClass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClearClass1ActionPerformed

    private void DeleteSppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteSppActionPerformed
        // TODO add your handling code here:
        int selectedRow = TableSpp.getSelectedRow();
        String ID = (String) TableSpp.getValueAt(selectedRow, 0);
        DefaultTableModel tableModel = (DefaultTableModel) TableSpp.getModel();

        Spp_controller controller = new Spp_controller();
        controller.deleteSppAction(selectedRow, ID, tableModel);
    }//GEN-LAST:event_DeleteSppActionPerformed

    private void UpdateSppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateSppActionPerformed
        // TODO add your handling code here:
        Integer Tahun = Integer.parseInt(SppTahunColumn.getText());
        Double Nominal = Double.parseDouble(SppNominalColumn.getText());
        int selectedRow = TableSpp.getSelectedRow();
        String ID = (String) TableSpp.getValueAt(selectedRow, 0);
        DefaultTableModel tableModel = (DefaultTableModel) TableSpp.getModel();

        try {
            if (Tahun == null || Nominal == null) {
                JOptionPane.showMessageDialog(null, "Error: Input cannot be empty.");
                return;
            } else {
                Spp_controller controller = new Spp_controller();
                controller.updateSppAction(Tahun, Nominal, selectedRow, ID, tableModel);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Error: Invalid input. Please enter valid numbers for Tahun and Nominal.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_UpdateSppActionPerformed

    private void SimpanSppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanSppActionPerformed
        // TODO add your handling code here:
        try {
            Integer Tahun = Integer.parseInt(SppTahunColumn.getText());
            Double Nominal = Double.parseDouble(SppNominalColumn.getText());

            DefaultTableModel tableModel = (DefaultTableModel) TableSpp.getModel();

            if (Tahun == null || Nominal == null) {
                JOptionPane.showMessageDialog(null, "Error: Input cannot be empty.");
                return;
            } else {
                Spp_controller controller = new Spp_controller();
                controller.insertSppAction(Tahun, Nominal, tableModel);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Error: Invalid input. Please enter valid numbers for Tahun and Nominal.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_SimpanSppActionPerformed

    private void TableSppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableSppMouseClicked
        // TODO add your handling code here:
        Integer row = TableSpp.getSelectedRow();

        if (row < 0) {
        } else {
            String ID = (String) TableSpp.getValueAt(row, 0);
            SELECT_DATABASE table = new SELECT_DATABASE();
            ResultSet data = table.getOneData("Spp", ID);

            try {
                if (data.next()) {

                    Integer Tahun = data.getInt("Tahun");
                    Double Nominal = data.getDouble("Nominal");

                    SppTahunColumn.setText(Tahun.toString());
                    SppNominalColumn.setText(Nominal.toString());

                } else {
                    System.out.println("Tidak ada data yang ditemukan.");
                }
            } catch (SQLException ex) {
                Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    if (data != null) {
                        data.close();
                    }
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_TableSppMouseClicked

    private void ClearClass2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearClass2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClearClass2ActionPerformed

    private void DeletePetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletePetugasActionPerformed
        // TODO add your handling code here:
        int selectedRow = TablePetugas.getSelectedRow();
        String ID = (String) TablePetugas.getValueAt(selectedRow, 0);
        DefaultTableModel tableModel = (DefaultTableModel) TablePetugas.getModel();

        Petugas_controller controller = new Petugas_controller();
        controller.deletePetugasAction(selectedRow, ID, tableModel);
    }//GEN-LAST:event_DeletePetugasActionPerformed

    private void UpdatePetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatePetugasActionPerformed
        // TODO add your handling code here:
        String Username = PetugasUsernameColumn.getText();
        String Name = PetugasNameColumn.getText();
        String Level = PetugasLevelColumn.getText();
        DefaultTableModel tableModel = (DefaultTableModel) TablePetugas.getModel();
        int selectedRow = TablePetugas.getSelectedRow();
        String ID = (String) TablePetugas.getValueAt(selectedRow, 0);

        if (Username.isEmpty() || Name.isEmpty() || Level.isEmpty()) {
            JOptionPane.showConfirmDialog(null, "Error: Input cannot be empty.");
            return;
        } else {
            Petugas_controller controller = new Petugas_controller();
            controller.updatePetugasAction(Username, "password", Name, Level, selectedRow, ID, tableModel);
        }

    }//GEN-LAST:event_UpdatePetugasActionPerformed

    private void SimpanPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanPetugasActionPerformed
        // TODO add your handling code here:
        String Username = PetugasUsernameColumn.getText();
        String Name = PetugasNameColumn.getText();
        String Level = PetugasLevelColumn.getText();
        DefaultTableModel tableModel = (DefaultTableModel) TablePetugas.getModel();

        if (Username.isEmpty() || Name.isEmpty() || Level.isEmpty()) {
            JOptionPane.showConfirmDialog(null, "Error: Input cannot be empty.");
            return;
        } else {
            Petugas_controller controller = new Petugas_controller();
            controller.insertPetugasAction(Username, "password", Name, Level, tableModel);
        }
    }//GEN-LAST:event_SimpanPetugasActionPerformed

    private void TablePetugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablePetugasMouseClicked
        // TODO add your handling code here:
        Integer row = TablePetugas.getSelectedRow();

        if (row < 0) {
        } else {
            String ID = (String) TablePetugas.getValueAt(row, 0);
            SELECT_DATABASE table = new SELECT_DATABASE();
            ResultSet data = table.getOneData("Petugas", ID);

            try {
                if (data.next()) {
                    String Username = data.getString("username");
                    String Nama_petugas = data.getString("nama_petugas");
                    String Level = data.getString("level");

                    PetugasUsernameColumn.setText(Username);
                    PetugasNameColumn.setText(Nama_petugas);
                    PetugasLevelColumn.setText(Level);

                } else {
                    System.out.println("Tidak ada data yang ditemukan.");
                }
            } catch (SQLException ex) {
                Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    if (data != null) {
                        data.close();
                    }
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_TablePetugasMouseClicked

    private void ClearClass3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearClass3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClearClass3ActionPerformed

    private void DeleteSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteSiswaActionPerformed
        // TODO add your handling code here:
        try {
            String data_spp = null;
            String data_kelas = null;
            String data_spp_name = null;
            String data_kelas_name = null;
            int selectedRow = TableSiswa.getSelectedRow();
            String ID = (String) TableSiswa.getValueAt(selectedRow, 0);
            DefaultTableModel tableModel = (DefaultTableModel) TableSiswa.getModel();

            String spp = (String) SiswaSppColumnItem.getSelectedItem();
            String kelas = (String) SiswaKelasColumnItem.getSelectedItem();

            ResultSet id_spp = new Siswa_controller().getOneSpp(spp);
            ResultSet id_kelas = new Siswa_controller().getOneKelas(kelas);

            if (id_spp.next() || id_kelas.next()) {
                data_spp = id_spp.getString("ID");
                data_kelas = id_kelas.getString("ID");
                data_spp_name = Integer.toString(id_spp.getInt("Tahun"));
                data_kelas_name = id_kelas.getString("Nama");
            }

            Siswa_controller controller = new Siswa_controller();
            controller.deleteSiswaAction(data_spp_name, data_kelas_name, selectedRow, ID, tableModel);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_DeleteSiswaActionPerformed

    private void UpdateSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateSiswaActionPerformed
        // TODO add your handling code here:
        try {

            String data_spp = null;
            String data_kelas = null;
            String data_spp_name = null;
            String data_kelas_name = null;

            String nisn = SiswaNisnColumn.getText();
            String nis = SiswaNisColumn.getText();
            String name = SiswaNameColumn.getText();
            String alamat = SiswaAlamatColumn.getText();
            String telp = SiswaTelpColumn.getText();
            String spp = (String) SiswaSppColumnItem.getSelectedItem();
            String kelas = (String) SiswaKelasColumnItem.getSelectedItem();
            DefaultTableModel tableModel = (DefaultTableModel) TableSiswa.getModel();
            int selectedRow = TableSiswa.getSelectedRow();
            String ID = (String) TableSiswa.getValueAt(selectedRow, 0);

            ResultSet id_spp = new Siswa_controller().getOneSpp(spp);
            ResultSet id_kelas = new Siswa_controller().getOneKelas(kelas);

            if (id_spp.next() || id_kelas.next()) {
                data_spp = id_spp.getString("ID");
                data_kelas = id_kelas.getString("ID");
                data_spp_name = Integer.toString(id_spp.getInt("Tahun"));
                data_kelas_name = id_kelas.getString("Nama");
            }

            Integer tlp = Integer.parseInt(telp);

            if (nisn.isEmpty() || nis.isEmpty() || name.isEmpty() || alamat.isEmpty() || telp.isEmpty() || nis.isEmpty() || nis.isEmpty() && tlp instanceof Integer) {
                JOptionPane.showConfirmDialog(null, "Error: Input cannot be empty.");
                return;
            } else {
                Siswa_controller controller = new Siswa_controller();
                controller.updateSiswaAction(data_spp_name, data_kelas_name, nisn, nis, name, alamat, tlp, data_spp, data_kelas, selectedRow, ID, tableModel);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_UpdateSiswaActionPerformed

    private void SimpanSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanSiswaActionPerformed
        // TODO add your handling code here:
        try {
            String data_spp = null;
            String data_kelas = null;
            String data_spp_name = null;
            String data_kelas_name = null;

            String nisn = SiswaNisnColumn.getText();
            String nis = SiswaNisColumn.getText();
            String name = SiswaNameColumn.getText();
            String alamat = SiswaAlamatColumn.getText();
            String telp = SiswaTelpColumn.getText();
            DefaultTableModel tableModel = (DefaultTableModel) TableSiswa.getModel();

            String spp = (String) SiswaSppColumnItem.getSelectedItem();
            String kelas = (String) SiswaKelasColumnItem.getSelectedItem();

            ResultSet id_spp = new Siswa_controller().getOneSpp(spp);
            ResultSet id_kelas = new Siswa_controller().getOneKelas(kelas);

            Integer tlp = Integer.parseInt(telp);

            if (id_spp.next() || id_kelas.next()) {
                data_spp = id_spp.getString("ID");
                data_kelas = id_kelas.getString("ID");
                data_spp_name = Integer.toString(id_spp.getInt("Tahun"));
                data_kelas_name = id_kelas.getString("Nama");
            }

            if (nisn.isEmpty() || nis.isEmpty() || name.isEmpty() || alamat.isEmpty() || telp.isEmpty() || nis.isEmpty() || nis.isEmpty() && tlp instanceof Integer) {
                JOptionPane.showConfirmDialog(null, "Error: Input cannot be empty or data types.");
                return;
            } else {
                new Siswa_controller().insertSiswaAction(data_spp_name, data_kelas_name, nisn.toString(), nis.toString(), name, alamat, tlp, data_spp, data_kelas, tableModel);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_SimpanSiswaActionPerformed

    private void TableSiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableSiswaMouseClicked
        // TODO add your handling code here:
        Integer row = TableSiswa.getSelectedRow();

        if (row < 0) {
        } else {
            String ID = (String) TableSiswa.getValueAt(row, 0);
            SELECT_DATABASE table = new SELECT_DATABASE();
            ResultSet data = table.getOneDatabyUuid("Siswa", ID);

            try {
                if (data.next()) {
                    String nisn = data.getString("nisn");
                    String nis = data.getString("nis");
                    String nama = data.getString("nama");
                    String alamat = data.getString("alamat");
                    String no_tlp = data.getString("no_tlp");
                    String id_spp = data.getString("id_spp");
                    String id_kelas = data.getString("id_kelas");

                    ResultSet spp = new Siswa_controller().getOneSpp(id_spp);
                    ResultSet kelas = new Siswa_controller().getOneKelas(id_kelas);

                    String idSpp = TableSiswa.getValueAt(row, 6).toString();
                    String idKelas = TableSiswa.getValueAt(row, 7).toString();

                    System.out.println("id Spp table = " + idSpp);
                    System.out.println("id Kelas table = " + idKelas);

                    SiswaNisnColumn.setText(nisn);
                    SiswaNisColumn.setText(nis);
                    SiswaNameColumn.setText(nama);
                    SiswaAlamatColumn.setText(alamat);
                    SiswaTelpColumn.setText(no_tlp);

                    SiswaSppColumnItem.setSelectedItem(idSpp);
                    SiswaKelasColumnItem.setSelectedItem(id_kelas);

                } else {
                    System.out.println("Tidak ada data yang ditemukan.");
                }
            } catch (SQLException ex) {
                Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    if (data != null) {
                        data.close();
                    }
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_TableSiswaMouseClicked

    private void SiswaKelasColumnItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiswaKelasColumnItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SiswaKelasColumnItemActionPerformed

    private void SiswaNameColumnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiswaNameColumnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SiswaNameColumnActionPerformed

    private void ClearClass4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearClass4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClearClass4ActionPerformed

    private void DeleteSiswa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteSiswa1ActionPerformed
        // TODO add your handling code here:
        try {
            int selectedRow = TablePembayaran.getSelectedRow();
            String ID = (String) TablePembayaran.getValueAt(selectedRow, 0);
            DefaultTableModel tableModel = (DefaultTableModel) TablePembayaran.getModel();
            
            pembayaran_controller controller = new pembayaran_controller();
            controller.deletePembayaranAction(selectedRow, ID, tableModel);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_DeleteSiswa1ActionPerformed

    private void UpdateSiswa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateSiswa1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_UpdateSiswa1ActionPerformed

    private void SimpanPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanPembayaranActionPerformed
        // TODO add your handling code here:
        try {
            String petugasID = null;
            String siswaID = null;
            String sppID = null;
            String petugasUsername = null;
            String siswaName = null;
            String sppTahun = null;

            Date selectedDate = jDatePembayaran.getDate();
            Calendar calendar = Calendar.getInstance();

            System.out.println("calendar" + calendar);

            String year = Integer.toString(calendar.get(Calendar.YEAR));
            String month = getMonthName(selectedDate);
            String day = Integer.toString(calendar.get(Calendar.DAY_OF_MONTH));
            String date = year + "-" + (calendar.get(Calendar.MONTH) + 1) + "-" + day;

            System.out.println("date: " + date);
            System.out.println("Year: " + year);
            System.out.println("Month: " + month);
            System.out.println("Day: " + day);

            String nominal = PembayaranNominalColumn.getText();

            Integer pembayaran = Integer.parseInt(nominal);

            String petugas = (String) PembayaranPetugasColumn.getSelectedItem();
            String siswa = (String) PembayaranSiswaColumn.getSelectedItem();
            String spp = (String) PembayaranSppColumn.getSelectedItem();
            DefaultTableModel tableModel = (DefaultTableModel) TablePembayaran.getModel();

            ResultSet id_petugas = new pembayaran_controller().getOnePetugas(petugas);
            ResultSet id_siswa = new pembayaran_controller().getOneSiswa(siswa);
            ResultSet id_spp = new pembayaran_controller().getOneSpp(spp);

            if (id_petugas.next() && id_siswa.next() && id_spp.next()) {
                petugasID = id_petugas.getString("ID");
                siswaID = id_siswa.getString("uuid");
                sppID = id_spp.getString("ID");

                petugasUsername = id_petugas.getString("username");
                siswaName = id_siswa.getString("nama");
                sppTahun = id_spp.getString("tahun");
            }

            if (nominal.isEmpty() && pembayaran instanceof Integer) {
                JOptionPane.showConfirmDialog(null, "Error: Input cannot be empty.");
                return;
            } else {
                new pembayaran_controller().insertPembayaranAction(petugasID, siswaID, date, month, year, sppID, pembayaran, tableModel);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

    }//GEN-LAST:event_SimpanPembayaranActionPerformed

    private void TablePembayaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablePembayaranMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TablePembayaranMouseClicked

    private void PembayaranPetugasColumnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PembayaranPetugasColumnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PembayaranPetugasColumnActionPerformed

    private void PembayaranSiswaColumnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PembayaranSiswaColumnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PembayaranSiswaColumnActionPerformed

    private void PembayaranSppColumnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PembayaranSppColumnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PembayaranSppColumnActionPerformed

    public void fillComboBoxKelas() {
        SwingUtilities.invokeLater(() -> {
            try {
                SiswaKelasColumnItem.removeAllItems();
                Siswa_controller controller = new Siswa_controller();
                List<String> data = controller.getAllKelas();

                for (String item : data) {
                    SiswaKelasColumnItem.addItem(item);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        });

    }

    public void fillComboBoxSpp() {
        SwingUtilities.invokeLater(() -> {
            try {
                SiswaSppColumnItem.removeAllItems();
                Siswa_controller controller = new Siswa_controller();
                List<String> data = controller.getAllSpp();

                for (String item : data) {
                    SiswaSppColumnItem.addItem(item);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        });

    }

    public void fillComboBoxPetugas() {
        SwingUtilities.invokeLater(() -> {
            try {
                PembayaranPetugasColumn.removeAllItems();
                pembayaran_controller controller = new pembayaran_controller();
                List<String> data = controller.getAllpetugas();

                for (String item : data) {
                    PembayaranPetugasColumn.addItem(item);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        });

    }

    public void fillComboBoxSiswa() {
        SwingUtilities.invokeLater(() -> {
            try {
                PembayaranSiswaColumn.removeAllItems();
                pembayaran_controller controller = new pembayaran_controller();
                List<String> data = controller.getAllSiswa();

                for (String item : data) {
                    PembayaranSiswaColumn.addItem(item);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        });

    }

    public void fillComboBoxSppPembayaran() {
        SwingUtilities.invokeLater(() -> {
            try {
                PembayaranSppColumn.removeAllItems();
                pembayaran_controller controller = new pembayaran_controller();
                List<String> data = controller.getAllSpp();

                for (String item : data) {
                    PembayaranSppColumn.addItem(item);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        });

    }

    public static String getMonthName(Date date) {
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(date);

        int monthNumber = calendar.get(Calendar.MONTH);

        DateFormatSymbols dfs = new DateFormatSymbols();
        String[] monthNames = dfs.getMonths();

        if (monthNumber >= 0 && monthNumber <= 11) {
            return monthNames[monthNumber];
        } else {
            throw new IllegalArgumentException("Invalid month number");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ClassNameColumn;
    private javax.swing.JButton ClearClass;
    private javax.swing.JButton ClearClass1;
    private javax.swing.JButton ClearClass2;
    private javax.swing.JButton ClearClass3;
    private javax.swing.JButton ClearClass4;
    private javax.swing.JTabbedPane DASHBOARD;
    private javax.swing.JButton DeleteClass;
    private javax.swing.JButton DeletePetugas;
    private javax.swing.JButton DeleteSiswa;
    private javax.swing.JButton DeleteSiswa1;
    private javax.swing.JButton DeleteSpp;
    private javax.swing.JTextField KopetensiColumn;
    private javax.swing.JTextField PembayaranNominalColumn;
    private javax.swing.JComboBox<String> PembayaranPetugasColumn;
    private javax.swing.JComboBox<String> PembayaranSiswaColumn;
    private javax.swing.JComboBox<String> PembayaranSppColumn;
    private javax.swing.JLabel Petugas;
    private javax.swing.JTextField PetugasLevelColumn;
    private javax.swing.JTextField PetugasNameColumn;
    private javax.swing.JTextField PetugasUsernameColumn;
    private javax.swing.JButton SimpanClass;
    private javax.swing.JButton SimpanPembayaran;
    private javax.swing.JButton SimpanPetugas;
    private javax.swing.JButton SimpanSiswa;
    private javax.swing.JButton SimpanSpp;
    private javax.swing.JTextField SiswaAlamatColumn;
    private javax.swing.JComboBox<String> SiswaKelasColumnItem;
    private javax.swing.JTextField SiswaNameColumn;
    private javax.swing.JTextField SiswaNisColumn;
    private javax.swing.JTextField SiswaNisnColumn;
    private javax.swing.JComboBox<String> SiswaSppColumnItem;
    private javax.swing.JTextField SiswaTelpColumn;
    private javax.swing.JTextField SppNominalColumn;
    private javax.swing.JTextField SppTahunColumn;
    private javax.swing.JTable TableClass;
    private javax.swing.JTable TablePembayaran;
    private javax.swing.JTable TablePetugas;
    private javax.swing.JTable TableSiswa;
    private javax.swing.JTable TableSpp;
    private javax.swing.JButton UpdateClass;
    private javax.swing.JButton UpdatePetugas;
    private javax.swing.JButton UpdateSiswa;
    private javax.swing.JButton UpdateSiswa1;
    private javax.swing.JButton UpdateSpp;
    private org.jdatepicker.impl.DateComponentFormatter dateComponentFormatter1;
    private org.jdatepicker.impl.DateComponentFormatter dateComponentFormatter2;
    private org.jdatepicker.impl.DateComponentFormatter dateComponentFormatter3;
    private org.jdatepicker.JDateComponentFactory jDateComponentFactory1;
    private com.toedter.calendar.JDateChooser jDatePembayaran;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil1;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil10;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil2;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil3;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil4;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil5;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil6;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil7;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil8;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    // End of variables declaration//GEN-END:variables
}
